#server:
#  port: 8011
#spring:
#  application:
#    name: product
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://172.16.30.103:3306/sell?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: 172.16.30.103
#    port: 6379
#    password:
#
#eureka:
#  client:
#    serviceUrl:
##      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://${eurekaServer.host1.hostName}:${eurekaServer.host1.port}/eureka/
#
#eurekaServer:
#  host1:
#    hostName: 119.27.175.187
#    port: 8761
##设置 Ribbon 负载均衡策略 RandomRule:随机，默认是 RoundRobinRule:轮询
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
spring:
  zipkin:
    base-url: http://172.16.30.103:9411
#    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
#    web:
#      client:
#        enabled: true
